name: Build

# events but only for the master branch
on:
  push:
    branches: [master]

jobs:

  build_and_deploy_package:
    runs-on: ubuntu-latest
    steps:
      
    # Checks-out the repo on branch master (default) under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    - name: Setup, build and publish
      env:
        PUBLIC_GIT_KEY: ${{ secrets.PUBLIC_GIT_KEY }}
      run: |
        cd $GITHUB_WORKSPACE
        yarn install
        yarn build
        yarn publish

